In [1]:
import os

BASE_DIR = "/kaggle/input/stanford-rna-3d-folding-2"

for root, hooked_dirs, files in os.walk(BASE_DIR):
    print(root)
    for f in files:
        print("  ", f)
    break  # まずはトップ階層だけ

/kaggle/input/stanford-rna-3d-folding-2
   sample_submission.csv
   validation_sequences.csv
   test_sequences.csv
   validation_labels.csv
   train_labels.csv
   train_sequences.csv

In [2]:
import pandas as pd

from tqdm.notebook import tqdm

In [3]:
import runpy

module_globals = runpy.run_path("/kaggle/usr/lib/tm-score-permutechains/metric.py")
score = module_globals['score']

## test_sequences

In [4]:
test_seq = pd.read_csv(f"{BASE_DIR}/test_sequences.csv")
test_seq.head()

,target_id,sequence,temporal_cutoff,description,stoichiometry,all_sequences,ligand_ids,ligand_SMILES
0,8ZNQ,ACCGUGACGGGCCUUUUGGCUAUACGCGGU,2025-06-04,Solution structure of the complex of naphthyri...,A:1,>8ZNQ_1|Chain A[auth A]|RNA (30-MER)|\nACCGUGA...,NAZ,Cc1ccc2ccc(nc2n1)NC(=O)CCNCCC(=O)NCc3ccc4c(n3)...
1,9IWF,GGUGUAUAAGCUCAUUAAUACGGUUUGAGCGUUUCGACCAGGCAAC...,2025-06-04,crystal structure of P. beijingensis xanthine-...,A:1,>9IWF_1|Chain A[auth A]|P. beijingensis xanthi...,GTP;MG;XAN,c1nc2c(n1[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=...
2,9JGM,GGAAGGGGAGUAACUUCAUUGCCGGUCGAUCGUCAUUACGAUGUGU...,2025-06-04,The Escherichia coli yybp riboswitch as a tand...,C:2,">9JGM_1|Chains A[auth C], C[auth D]|yybP ribos...",MG;MN,[Mg+2];[Mn+2]
3,9MME,UAUUUGAAUCAUACCUGCGAUCAACUCGAUGAAUAAAGUACGCCAG...,2025-06-04,ROOLfirm-octamer-wild type,U:8,">9MME_1|Chains A[auth U], B[auth Y], C[auth c]...",K;MG,[K+];[Mg+2]
4,9J09,CUUUUUGACGAAAAACUCGCCUCAGAAGAUAGGGAGAGUCUAAACG...,2025-06-04,Cryo-EM structure of the RdCas12n-sgRNA-DNA co...,R:1,>9J09_4|Chain D[auth R]|sgRNA|\nCUUUUUGACGAAAA...,NaN,NaN

In [5]:
test_seq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   target_id        28 non-null     object
 1   sequence         28 non-null     object
 2   temporal_cutoff  28 non-null     object
 3   description      28 non-null     object
 4   stoichiometry    28 non-null     object
 5   all_sequences    28 non-null     object
 6   ligand_ids       14 non-null     object
 7   ligand_SMILES    14 non-null     object
dtypes: object(8)
memory usage: 1.9+ KB

## validation_labels.csv

In [6]:
valid_labels = pd.read_csv(f"{BASE_DIR}/validation_labels.csv", low_memory=False)
valid_labels.head()

,ID,resname,resid,x_1,y_1,z_1,x_2,y_2,z_2,x_3,...,z_38,x_39,y_39,z_39,x_40,y_40,z_40,chain,copy,Usage
0,8ZNQ_1,A,1,-2.054,-15.062,20.736,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,A,1,Public
1,8ZNQ_2,C,2,-1.971,-15.076,15.338,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,A,1,Public
2,8ZNQ_3,C,3,-3.350,-13.497,10.444,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,A,1,Public
3,8ZNQ_4,G,4,-5.443,-11.044,6.605,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,A,1,Public
4,8ZNQ_5,U,5,-6.350,-6.269,4.550,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,...,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,-1.000000e+18,A,1,Public

## validation_sequences.csv

In [7]:
valid_seq = pd.read_csv(f"{BASE_DIR}/validation_sequences.csv")
valid_seq.head()

,target_id,sequence,temporal_cutoff,description,stoichiometry,all_sequences,ligand_ids,ligand_SMILES
0,8ZNQ,ACCGUGACGGGCCUUUUGGCUAUACGCGGU,2025-06-04,Solution structure of the complex of naphthyri...,A:1,>8ZNQ_1|Chain A[auth A]|RNA (30-MER)|\nACCGUGA...,NAZ,Cc1ccc2ccc(nc2n1)NC(=O)CCNCCC(=O)NCc3ccc4c(n3)...
1,9IWF,GGUGUAUAAGCUCAUUAAUACGGUUUGAGCGUUUCGACCAGGCAAC...,2025-06-04,crystal structure of P. beijingensis xanthine-...,A:1,>9IWF_1|Chain A[auth A]|P. beijingensis xanthi...,GTP;MG;XAN,c1nc2c(n1[C@H]3[C@@H]([C@@H]([C@H](O3)CO[P@](=...
2,9JGM,GGAAGGGGAGUAACUUCAUUGCCGGUCGAUCGUCAUUACGAUGUGU...,2025-06-04,The Escherichia coli yybp riboswitch as a tand...,C:2,">9JGM_1|Chains A[auth C], C[auth D]|yybP ribos...",MG;MN,[Mg+2];[Mn+2]
3,9MME,UAUUUGAAUCAUACCUGCGAUCAACUCGAUGAAUAAAGUACGCCAG...,2025-06-04,ROOLfirm-octamer-wild type,U:8,">9MME_1|Chains A[auth U], B[auth Y], C[auth c]...",K;MG,[K+];[Mg+2]
4,9J09,CUUUUUGACGAAAAACUCGCCUCAGAAGAUAGGGAGAGUCUAAACG...,2025-06-04,Cryo-EM structure of the RdCas12n-sgRNA-DNA co...,R:1,>9J09_4|Chain D[auth R]|sgRNA|\nCUUUUUGACGAAAA...,NaN,NaN

In [8]:
def make_linear_baseline_submission(seq_df, n_structures=5, show_progress=True):
    """
    seq_df: DataFrame with columns [target_id, sequence]
    n_structures: number of predicted structures (default=5)
    
    returns: submission-style DataFrame
    """

    rows = []

    iterator = tqdm(seq_df.iterrows(), total=len(seq_df)) if show_progress else seq_df.iterrows()

    for _, r in iterator:
        tid = r["target_id"]
        seq = r["sequence"]

        for i, base in enumerate(seq):
            resid = i + 1

            row = {
                "ID": f"{tid}_{resid}",
                "resname": base,
                "resid": resid,
            }

            # straight line baseline
            for k in range(1, n_structures + 1):
                row[f"x_{k}"] = resid
                row[f"y_{k}"] = 0.0
                row[f"z_{k}"] = 0.0

            rows.append(row)

    return pd.DataFrame(rows)

In [9]:
valid_sub = make_linear_baseline_submission(valid_seq)

  0%|          | 0/28 [00:00<?, ?it/s]

In [10]:
valid_sub.head()

,ID,resname,resid,x_1,y_1,z_1,x_2,y_2,z_2,x_3,y_3,z_3,x_4,y_4,z_4,x_5,y_5,z_5
0,8ZNQ_1,A,1,1,0.0,0.0,1,0.0,0.0,1,0.0,0.0,1,0.0,0.0,1,0.0,0.0
1,8ZNQ_2,C,2,2,0.0,0.0,2,0.0,0.0,2,0.0,0.0,2,0.0,0.0,2,0.0,0.0
2,8ZNQ_3,C,3,3,0.0,0.0,3,0.0,0.0,3,0.0,0.0,3,0.0,0.0,3,0.0,0.0
3,8ZNQ_4,G,4,4,0.0,0.0,4,0.0,0.0,4,0.0,0.0,4,0.0,0.0,4,0.0,0.0
4,8ZNQ_5,U,5,5,0.0,0.0,5,0.0,0.0,5,0.0,0.0,5,0.0,0.0,5,0.0,0.0

## train_sequences.csv

In [11]:
# train_seq = pd.read_csv(f"{BASE_DIR}/train_sequences.csv")
# train_seq.head()

In [12]:
# train_seq.info()

In [13]:
# # 配列長の確認
# train_seq["seq_len"] = train_seq["sequence"].str.len()
# train_seq["seq_len"].describe()

## train_labels.csv

In [14]:
# train_labels = pd.read_csv(f"{BASE_DIR}/train_labels.csv", low_memory=False)
# train_labels.head()

In [15]:
# train_labels.info()

In [16]:
# train_labels.sample(5)

In [17]:
# train_labels["target_id"] = train_labels["ID"].apply(lambda x: x.split("_")[0])
# train_labels.groupby("target_id").size().head()

In [18]:
# # residue数と一致するか確認
# tid = train_labels["target_id"].iloc[0]

# print(
#     tid,
#     len(train_labels[train_labels.target_id == tid]),
#     len(train_seq[train_seq.target_id == tid].sequence.iloc[0])
# )

## Evaluation

In [19]:
#　prepare groud truth
sol = valid_labels.copy()
sub = valid_sub.copy()

# extract target_id
sol['target_id'] = sol['ID'].apply(lambda x: '_'.join(str(x).split('_')[:-1]))
sub['target_id'] = sub['ID'].apply(lambda x: '_'.join(str(x).split('_')[:-1]))

In [20]:
results = []
for target_id, group_native in tqdm(sol.groupby('target_id')):
    group_predicted = sub[sub['target_id'] == target_id]

    result = score(group_native, group_predicted, 'ID')

    print(target_id, result)
    results.append(result)

print('Mean score:', sum(results)/len(results), f'(n={len(results)})')

  0%|          | 0/28 [00:00<?, ?it/s]

8ZNQ 0.04353
9CFN 0.05305
9E74 0.07863
9E75 0.07798
9E9Q 0.06756
9EBP 0.06805
9G4J 0.07157
9G4P 0.06878
9G4Q 0.07644
9G4R 0.04911
9HRO 0.0296
9I9W 0.03263
9IWF 0.06306
9J09 0.06455
9JFO 0.06798
9JFS 0.08073
9JGM 0.07426
9KGG 0.0719
9LEC 0.06851
9LEL 0.08886
9LJN 0.0714
9MME 0.03386
9OBM 0.04757
9OD4 0.02831
9QZJ 0.02488
9RVP 0.03873
9WHV 0.06008
9ZCC 0.07023
Mean score: 0.05970857142857143 (n=28)

## sample_submission.csv

In [21]:
# submission = pd.read_csv(f"{BASE_DIR}/sample_submission.csv")
# submission.head(50)

In [22]:
# sample_sub = submission.copy()
# sample_sub["target_id"] = sample_sub["ID"].apply(lambda x: x.split("_")[0])
# sample_sub["resid_from_id"] = sample_sub["ID"].apply(lambda x: int(x.split("_")[1]))

# sample_sub.head()

## Submission

In [23]:
test_sub = make_linear_baseline_submission(test_seq)

  0%|          | 0/28 [00:00<?, ?it/s]

In [24]:
test_sub.to_csv("submission.csv", index=False)